name: navbar

description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dependencies:
  flutter_calendar_week:
    git:
      url: https://github.com/mduccc/flutter_calendar_week
      ref: 0.4.1
  simple_animations: ^1.3.3
  timeline_tile: ^0.1.0
  cupertino_icons: ^0.1.2
  firebase_core: ^0.5.2+1
  firebase_auth: ^0.18.3+1
  google_sign_in: ^4.5.6
  flutter_signin_button: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  curved_navigation_bar: ^0.3.4
  page_transition: ^1.1.4

  rxdart: 0.23.1

  provider: 3.1.0
  transparent_image: 1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
